# Generated by Django 5.0.2 on 2024-05-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название товара')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Скидка')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('url_path', models.URLField(default='', verbose_name='Ссылка на товар')),
                ('url_img', models.URLField(default='', verbose_name='Ссылка на изображение')),
                ('image', models.ImageField(upload_to='img_product', verbose_name='Изображение')),
                ('article', models.CharField(default='', max_length=50, verbose_name='Артикуль')),
                ('gender', models.CharField(default='', max_length=50, verbose_name='Пол')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Страна')),
                ('waterproof', models.CharField(default='', max_length=50, verbose_name='Водостойкость')),
                ('type_mechanism', models.CharField(default='', max_length=50, verbose_name='Тип механизма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
