# Generated by Django 5.0.2 on 2024-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url_img',
            field=models.URLField(default='', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='url_path',
            field=models.URLField(default='', null=True, verbose_name='Ссылка на товар'),
        ),
    ]
