# Generated by Django 5.0.2 on 2024-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Электронная почта')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль')),
                ('password_check', models.CharField(default='', max_length=50, verbose_name='Повторить пароль')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
